/**
 * LunchBreakPanel
 * Shows the auto-generated lunch break schedule for all room staff.
 * Allows manual time overrides. Saves to Supabase for the Reg 151 report.
 */
import { useState, useEffect, useCallback } from 'react';
import type { RoomRatioStatus, FloatStaff, RosteredStaff } from '../types';
import type { LunchBreakEntry, LunchWindow } from '../utils/lunchScheduler';
import { generateLunchSchedule, DEFAULT_LUNCH_WINDOW } from '../utils/lunchScheduler';
import { loadCentreRules, getBreakWindow } from '../utils/centreRules';
import { minsToHHMM, hhmmToMins } from '../utils/timeUtils';

interface Props {
  centreId:       string;
  date:           string;
  roomStatuses:   RoomRatioStatus[];
  floats:         FloatStaff[];
  issStaff:       FloatStaff[];
  staffMoves:     Record<number, string>;
  supportStaff?:  RosteredStaff[];   // AD/Ed Leader - fallback cover when no float/ISS
  approvedPlaces?: number;           // If < 100, support staff may cover lunch
}

const STORAGE_KEY = (centreId: string, date: string) => `tga_lunch:${centreId}:${date}`;
const SUPABASE_URL = 'https://tgxpvzlibquqnldgmwho.supabase.co';
const ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRneHB2emxpYnF1cW5sZGdtd2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NDE3MjUsImV4cCI6MjA4OTUxNzcyNX0.v_thHOU7xq0gaFhcnb2A3iBl5H7bAp9IbT9IPMg_jTY';

async function loadSavedSchedule(centreId: string, date: string): Promise<LunchBreakEntry[] | null> {
  // Try localStorage first (fast)
  try {
    const raw = localStorage.getItem(STORAGE_KEY(centreId, date));
    if (raw) {
      // Also merge float schedule coverage on top of cached data
      const schedule = JSON.parse(raw) as LunchBreakEntry[];
      return await mergeFloatCoverage(centreId, date, schedule);
    }
  } catch { /* ignore */ }
  // Try Supabase
  try {
    const r = await fetch(
      `${SUPABASE_URL}/rest/v1/lunch_schedules?centre_id=eq.${encodeURIComponent(centreId)}&date=eq.${date}&select=schedule&limit=1`,
      { headers: { apikey: ANON_KEY, Authorization: `Bearer ${ANON_KEY}` } }
    );
    if (r.ok) {
      const rows = await r.json();
      if (rows?.length > 0 && rows[0].schedule) {
        const schedule = rows[0].schedule as LunchBreakEntry[];
        localStorage.setItem(STORAGE_KEY(centreId, date), JSON.stringify(schedule));
        return await mergeFloatCoverage(centreId, date, schedule);
      }
    }
  } catch { /* offline */ }
  return null;
}

/**
 * Merge float schedule break-cover blocks into the lunch schedule.
 * Float schedule is authoritative: whenever a float's Plan Day assigns them
 * to cover Staff Y’s lunch, that coverage populates the lunch panel immediately
 * regardless of what time was auto-generated.
 */
async function mergeFloatCoverage(centreId: string, date: string, schedule: LunchBreakEntry[]): Promise<LunchBreakEntry[]> {
  try {
    const r = await fetch(
      `${SUPABASE_URL}/rest/v1/float_schedules?centre_id=eq.${encodeURIComponent(centreId)}&date=eq.${date}&select=employee_id,employee_name,schedule`,
      { headers: { apikey: ANON_KEY, Authorization: `Bearer ${ANON_KEY}` } }
    );
    if (!r.ok) return schedule;
    const floatRows = await r.json();
    if (!Array.isArray(floatRows) || floatRows.length === 0) return schedule;

    // Build map: coveredEmployeeId → { floatName, lunchStart, lunchEnd }
    // Multiple floats may cover the same person at different times — keep most recent.
    const coverageMap = new Map<number, { floatName: string; floatId: number; start: string; end: string }>();
    for (const row of floatRows) {
      const blocks: any[] = row.schedule ?? [];
      for (const block of blocks) {
        if (block.coveringEmployeeId && block.startTime && block.endTime) {
          coverageMap.set(block.coveringEmployeeId, {
            floatName: row.employee_name ?? '',
            floatId:   row.employee_id   ?? 0,
            start:     block.startTime,
            end:       block.endTime,
          });
        }
      }
    }

    if (coverageMap.size === 0) return schedule;

    // Apply coverage — float schedule is authoritative: use float's actual times,
    // overriding any auto-generated lunch time. No timesMatch check.
    return schedule.map((entry): LunchBreakEntry => {
      const cov = coverageMap.get(entry.employeeId);
      if (!cov) return entry;
      return {
        ...entry,
        lunchStart:    cov.start,   // float’s coverage time is the actual break time
        lunchEnd:      cov.end,
        coveredBy:     { employeeId: cov.floatId, name: cov.floatName, type: 'float' as const },
        autoGenerated: false,
      };
    });
  } catch {
    return schedule;
  }
}

async function saveSchedule(centreId: string, date: string, schedule: LunchBreakEntry[]): Promise<void> {
  localStorage.setItem(STORAGE_KEY(centreId, date), JSON.stringify(schedule));
  try {
    await fetch(`${SUPABASE_URL}/rest/v1/lunch_schedules`, {
      method: 'POST',
      headers: {
        apikey: ANON_KEY,
        Authorization: `Bearer ${ANON_KEY}`,
        'Content-Type': 'application/json',
        Prefer: 'resolution=merge-duplicates',
      },
      body: JSON.stringify({ centre_id: centreId, date, schedule }),
    });
  } catch { /* offline - local saved */ }
}

// ─── Time editor ─────────────────────────────────────────────────────────────

function TimeEditor({
  value, onChange, min, max,
}: {
  value: string; onChange: (v: string) => void; min?: string; max?: string;
}) {
  return (
    <input
      type="time"
      value={value}
      min={min}
      max={max}
      onChange={e => onChange(e.target.value)}
      className="text-xs border rounded-lg px-1.5 py-1 w-20"
      style={{ borderColor: '#D0E8B8', color: '#2d5c18' }}
    />
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

export default function LunchBreakPanel({ centreId, date, roomStatuses, floats, issStaff, staffMoves, supportStaff = [], approvedPlaces }: Props) {
  const [schedule, setSchedule]   = useState<LunchBreakEntry[]>([]);
  const [window_, setWindow]      = useState<LunchWindow>(DEFAULT_LUNCH_WINDOW);
  const [loading, setLoading]     = useState(true);
  const [saving, setSaving]       = useState(false);
  const [saved, setSaved]         = useState(false);
  const [editing, setEditing]     = useState<number | null>(null); // employeeId being edited
  const [collapsed, setCollapsed] = useState(false);

  // Load centre rules first, THEN load saved schedule or auto-generate
  // (must be a single effect to avoid race: rules must be resolved before generation)
  useEffect(() => {
    if (roomStatuses.length === 0) return;
    setLoading(true);

    async function init() {
      // 1. Resolve the lunch window from centre rules
      let resolvedWindow = DEFAULT_LUNCH_WINDOW;
      try {
        const rules = await loadCentreRules();
        const w = getBreakWindow('lunch', centreId, rules);
        if (w) {
          resolvedWindow = { start: w.start, end: w.end, durationMins: w.durationMins };
          setWindow(resolvedWindow);
        }
      } catch { /* use default */ }

      // 2. Always generate a fresh base from current room staff so every rostered
      //    educator appears in the list (prevents stale saved schedules from hiding
      //    newly-rostered staff).
      const freshBase = generateLunchSchedule(roomStatuses, floats, issStaff, staffMoves, resolvedWindow, supportStaff, approvedPlaces);

      // 3. Load any manually-saved time overrides from a previous session.
      //    We only borrow the lunchStart/lunchEnd from saved entries where the
      //    director explicitly adjusted times (autoGenerated = false, no coveredBy).
      //    Coverage is ALWAYS re-applied fresh from float schedules below.
      // Clear any auto-generated localStorage data from a previous bad auto-save
      // (today's date only — legacy cleanup for the auto-save that was removed).
      const savedRaw = localStorage.getItem(STORAGE_KEY(centreId, date));
      if (savedRaw) {
        try {
          const parsed = JSON.parse(savedRaw) as LunchBreakEntry[];
          // If every entry is auto-generated (no director edits), discard it
          const hasManualEdit = parsed.some(e => !e.autoGenerated);
          if (!hasManualEdit) localStorage.removeItem(STORAGE_KEY(centreId, date));
        } catch { localStorage.removeItem(STORAGE_KEY(centreId, date)); }
      }
      const saved = await loadSavedSchedule(centreId, date);
      const savedMap = new Map<number, LunchBreakEntry>(
        (saved ?? []).map(e => [e.employeeId, e])
      );
      const withOverrides: LunchBreakEntry[] = freshBase.map(entry => {
        const s = savedMap.get(entry.employeeId);
        // Apply a saved manual time only if the director explicitly changed it
        if (s && !s.autoGenerated && !s.coveredBy) {
          return { ...entry, lunchStart: s.lunchStart, lunchEnd: s.lunchEnd, autoGenerated: false };
        }
        return entry;
      });

      // 4. Apply float Plan Day coverage (always authoritative, no time-match guard).
      const merged = await mergeFloatCoverage(centreId, date, withOverrides);
      setSchedule(merged);
      setLoading(false);
    }

    init();
  }, [centreId, date, roomStatuses.length]); // eslint-disable-line

  const regenerate = useCallback(async () => {
    // Re-read rules in case they changed
    let resolvedWindow = window_;
    try {
      const rules = await loadCentreRules();
      const w = getBreakWindow('lunch', centreId, rules);
      if (w) {
        resolvedWindow = { start: w.start, end: w.end, durationMins: w.durationMins };
        setWindow(resolvedWindow);
      }
    } catch { /* keep current window */ }
    const generated = generateLunchSchedule(roomStatuses, floats, issStaff, staffMoves, resolvedWindow, supportStaff, approvedPlaces);
    // Always apply float Plan Day coverage after regeneration
    const merged = await mergeFloatCoverage(centreId, date, generated);
    setSchedule(merged);
    setSaved(false);
  }, [centreId, roomStatuses, floats, issStaff, staffMoves, window_]);

  const handleSave = async () => {
    setSaving(true);
    await saveSchedule(centreId, date, schedule);
    setSaving(false);
    setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  };

  const updateEntry = (employeeId: number, patch: Partial<LunchBreakEntry>) => {
    setSchedule(prev => prev.map(e =>
      e.employeeId === employeeId ? { ...e, ...patch, autoGenerated: false } : e
    ));
    setSaved(false);
  };

  const uncoveredCount = schedule.filter(e => e.needsCover && !e.coveredBy).length;
  const roomGroups = schedule.reduce<Record<string, LunchBreakEntry[]>>((acc, e) => {
    (acc[e.room] ??= []).push(e);
    return acc;
  }, {});

  return (
    <div className="rounded-2xl border overflow-hidden shadow-sm" style={{ borderColor: '#fde68a' }}>
      {/* Header */}
      <div
        className="px-4 py-3 flex items-center justify-between cursor-pointer select-none"
        style={{ backgroundColor: '#fffbeb' }}
        onClick={() => setCollapsed(c => !c)}
      >
        <div className="flex items-center gap-3">
          <span className="text-sm font-bold" style={{ color: '#92400e' }}>🍽 Lunch Break Plan</span>
          <span className="text-xs" style={{ color: '#b45309', opacity: 0.7 }}>auto-fills from float Plan Days</span>
          <span className="text-xs" style={{ color: '#b45309' }}>
            {window_.start}-{window_.end} · {window_.durationMins} min
          </span>
          {uncoveredCount > 0 && (
            <span className="text-xs px-2 py-0.5 rounded-full font-semibold"
              style={{ backgroundColor: '#fee2e2', color: '#dc2626' }}>
              ⚠ {uncoveredCount} uncovered
            </span>
          )}
        </div>
        <div className="flex items-center gap-2" onClick={e => e.stopPropagation()}>
          <button
            onClick={regenerate}
            className="text-xs px-2.5 py-1 rounded-lg border font-medium"
            style={{ borderColor: '#fde68a', color: '#92400e', backgroundColor: 'white' }}
            title="Re-generate from current roster"
          >
            ↺ Re-generate
          </button>
          <button
            onClick={handleSave}
            disabled={saving}
            className="text-xs px-3 py-1 rounded-lg font-semibold text-white"
            style={{ backgroundColor: saved ? '#16a34a' : '#d97706' }}
          >
            {saved ? '✓ Saved' : saving ? 'Saving...' : 'Save'}
          </button>
          <span className="text-xs" style={{ color: '#b45309' }}>{collapsed ? '▾' : '▴'}</span>
        </div>
      </div>

      {!collapsed && (
        <div className="bg-white">
          {loading ? (
            <div className="px-4 py-6 text-sm italic text-center" style={{ color: '#9ca3af' }}>Generating lunch schedule...</div>
          ) : schedule.length === 0 ? (
            <div className="px-4 py-6 text-sm italic text-center" style={{ color: '#9ca3af' }}>No room staff to schedule.</div>
          ) : (
            <div>
              {/* Column headers */}
              <div className="grid px-4 py-2 text-xs font-semibold uppercase tracking-wide border-b"
                style={{ gridTemplateColumns: '1fr 1fr', borderColor: '#fef3c7', backgroundColor: '#fffdf5', color: '#92400e' }}>
                <span>Staff member &amp; lunch time</span>
                <span>Who covers &amp; when they enter the room</span>
              </div>

              {/* Per-room groups */}
              {Object.entries(roomGroups).map(([room, entries]) => (
                <div key={room} className="border-b" style={{ borderColor: '#fde68a' }}>
                  {/* Room header */}
                  <div className="px-4 py-2 text-xs font-bold uppercase tracking-wide flex items-center gap-2"
                    style={{ backgroundColor: '#fef9c3', color: '#78350f' }}>
                    <span>📍 {room}</span>
                    <span className="font-normal opacity-60">· {entries.length} break{entries.length !== 1 ? 's' : ''} scheduled</span>
                  </div>

                  {/* Each lunch break - shown as a two-column handover row */}
                  {entries.map(entry => {
                    const isEditing = editing === entry.employeeId;
                    const coverType = entry.coveredBy?.type;
                    const coverColor = coverType === 'float' ? { bg: '#eff6ff', text: '#1d4ed8', border: '#bfdbfe', label: 'Float' }
                      : coverType === 'iss' ? { bg: '#f5f3ff', text: '#6d28d9', border: '#ddd6fe', label: 'ISS' }
                      : coverType === 'support' ? { bg: '#fff7ed', text: '#9a3412', border: '#fed7aa', label: 'AD / Ed Leader' }
                      : coverType === 'surplus' ? { bg: '#f0fdf4', text: '#166534', border: '#bbf7d0', label: 'Colleague' }
                      : { bg: '#fef2f2', text: '#dc2626', border: '#fca5a5', label: 'No cover' };

                    return (
                      <div key={entry.employeeId}
                        className="grid border-t"
                        style={{ gridTemplateColumns: '1fr 1fr', borderColor: '#fef3c7' }}>

                        {/* LEFT - person going on lunch */}
                        <div
                          className="px-4 py-3 flex flex-col gap-1 cursor-pointer hover:bg-amber-50 transition-colors"
                          style={{ borderRight: '1px solid #fef3c7' }}
                          onClick={() => setEditing(isEditing ? null : entry.employeeId)}
                        >
                          <div className="flex items-center gap-2">
                            <span className="text-sm font-semibold" style={{ color: '#111827' }}>{entry.name}</span>
                            {!entry.autoGenerated && (
                              <span className="text-xs px-1.5 py-0.5 rounded" style={{ backgroundColor: '#fef3c7', color: '#92400e' }}>edited</span>
                            )}
                          </div>
                          <div className="text-xs" style={{ color: '#9ca3af' }}>Shift {entry.shiftStart}-{entry.shiftEnd}</div>
                          {isEditing ? (
                            <div className="flex items-center gap-2 mt-1" onClick={e => e.stopPropagation()}>
                              <TimeEditor
                                value={entry.lunchStart}
                                min={window_.start}
                                max={minsToHHMM(hhmmToMins(entry.lunchEnd) - 15)}
                                onChange={v => updateEntry(entry.employeeId, {
                                  lunchStart: v,
                                  lunchEnd: minsToHHMM(hhmmToMins(v) + window_.durationMins),
                                })}
                              />
                              <span className="text-xs" style={{ color: '#6b7280' }}>→</span>
                              <TimeEditor
                                value={entry.lunchEnd}
                                min={minsToHHMM(hhmmToMins(entry.lunchStart) + 15)}
                                max={window_.end}
                                onChange={v => updateEntry(entry.employeeId, { lunchEnd: v })}
                              />
                            </div>
                          ) : (
                            <div className="flex items-center gap-1.5 mt-0.5">
                              <span className="text-base">🍽</span>
                              <span className="text-sm font-bold" style={{ color: '#d97706' }}>
                                {entry.lunchStart} - {entry.lunchEnd}
                              </span>
                              <span className="text-xs" style={{ color: '#9ca3af' }}>({window_.durationMins} min)</span>
                            </div>
                          )}
                        </div>

                        {/* RIGHT - cover person entering the room */}
                        <div className="px-4 py-3 flex flex-col gap-1" style={{ backgroundColor: entry.coveredBy ? coverColor.bg + '88' : '#fef2f2' }}>
                          {entry.coveredBy ? (
                            <>
                              <div className="flex items-center gap-2">
                                <span className="text-xs font-bold px-2 py-0.5 rounded-full border"
                                  style={{ backgroundColor: coverColor.bg, color: coverColor.text, borderColor: coverColor.border }}>
                                  {coverColor.label}
                                </span>
                                <span className="text-sm font-semibold" style={{ color: '#111827' }}>{entry.coveredBy.name}</span>
                              </div>
                              <div className="text-xs" style={{ color: '#6b7280' }}>
                                Enters <strong>{room}</strong>
                              </div>
                              <div className="flex items-center gap-1.5 mt-0.5">
                                <span className="text-base">↳</span>
                                <span className="text-sm font-bold" style={{ color: coverColor.text }}>
                                  {entry.lunchStart} - {entry.lunchEnd}
                                </span>
                                <span className="text-xs" style={{ color: '#9ca3af' }}>in this room</span>
                              </div>
                            </>
                          ) : (
                            <div className="flex flex-col gap-1">
                              <span className="text-xs font-semibold" style={{ color: '#dc2626' }}>⚠ No cover available</span>
                              <span className="text-xs" style={{ color: '#9ca3af' }}>Ratio may drop during this break.</span>
                              <span className="text-xs" style={{ color: '#9ca3af' }}>Assign a float to cover.</span>
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              ))}

              <div className="px-4 py-2 text-xs border-t" style={{ borderColor: '#fef3c7', color: '#9ca3af' }}>
                Coverage fills automatically as float Plan Days are saved · Click a time to manually adjust · Save to persist and sync with the Reg 151 report
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
