/**
 * Lunch Break Scheduler
 *
 * Automatically generates a staggered lunch break schedule for all room staff,
 * assigning float/ISS/surplus cover where needed.
 *
 * Rules:
 *  – Breaks are scheduled within the configured lunch window (e.g. 11:30–14:00)
 *  – Breaks are staggered so ratio compliance is maintained at all times
 *  – If a room has surplus staff, breaks are self-covered (no float needed)
 *  – If a room is at exact ratio (surplus = 0), floats/ISS are assigned to cover
 *  – Floats cover breaks SEQUENTIALLY and BACK-TO-BACK across ALL rooms
 *    (one float moves from room to room without idle gaps — not one float per room)
 *  – Breaks are only scheduled within the staff member's shift window
 */

import { hhmmToMins, minsToHHMM } from './timeUtils';
import type { RoomRatioStatus, FloatStaff, RosteredStaff } from '../types';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface LunchBreakEntry {
  employeeId:   number;
  name:         string;
  room:         string;            // room name they work in
  shiftStart:   string;            // HH:MM
  shiftEnd:     string;            // HH:MM
  lunchStart:   string;            // HH:MM — scheduled break start
  lunchEnd:     string;            // HH:MM — scheduled break end
  coveredBy:    CoverageInfo | null;
  needsCover:   boolean;           // true = ratio drops below minimum without cover
  autoGenerated: boolean;          // false = manually overridden
}

export interface CoverageInfo {
  name:        string;
  employeeId:  number;
  type:        'float' | 'iss' | 'surplus' | 'support';  // surplus = room colleague; support = AD/Ed Leader
}

export interface LunchWindow {
  start:        string;   // HH:MM
  end:          string;   // HH:MM
  durationMins: number;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Parse Deputy's unix-timestamp or HH:MM startTime to HH:MM */
function parseShiftTime(t: string | number): string {
  if (typeof t === 'number') {
    const d = new Date(t * 1000);
    const h = d.toLocaleString('en-AU', { hour: '2-digit', hour12: false, timeZone: 'Australia/Sydney' });
    const m = d.toLocaleString('en-AU', { minute: '2-digit', timeZone: 'Australia/Sydney' });
    return `${h.padStart(2,'0')}:${m.padStart(2,'0')}`;
  }
  return String(t).slice(0, 5);
}

/** Default lunch window if no centre rule configured */
export const DEFAULT_LUNCH_WINDOW: LunchWindow = {
  start:        '10:00',
  end:          '14:40',
  durationMins: 30,
};

// ─── Main scheduler ───────────────────────────────────────────────────────────

/** Unit name substrings that identify staff eligible to cover lunch when centre < 100 places */
const SUPPORT_COVER_ROLES = ['assistant director', 'educational leader', 'ed leader'];

export function generateLunchSchedule(
  roomStatuses:   RoomRatioStatus[],
  floats:         FloatStaff[],
  _issStaff:      FloatStaff[], // ISS self-manage breaks — excluded from cover pool
  _staffMoves:    Record<number, string>,
  lunchWindow:    LunchWindow,
  supportStaff:   RosteredStaff[] = [],
  approvedPlaces?: number,         // If < 100, ADs/Ed Leaders may cover lunch breaks
): LunchBreakEntry[] {
  const windowStart = hhmmToMins(lunchWindow.start);
  const windowEnd   = hhmmToMins(lunchWindow.end);
  const dur         = lunchWindow.durationMins;

  if (windowEnd - windowStart < dur) return [];

  // Pool of coverers — floats first, then ISS, then support (AD/Ed Leader if centre < 100 places)
  const canUseSupport = approvedPlaces === undefined || approvedPlaces < 100;
  const eligibleSupport = canUseSupport
    ? supportStaff.filter(s =>
        SUPPORT_COVER_ROLES.some(role => (s.unitName ?? '').toLowerCase().includes(role))
      )
    : [];

  const covererPool: {
    id: number; name: string; type: 'float' | 'iss' | 'support';
    nextAvailMins: number; shiftStartMins: number; shiftEndMins: number;
  }[] = [
    ...floats.map(f => ({
      id:             f.employeeId,
      name:           f.employeeName,
      type:           'float' as const,
      nextAvailMins:  windowStart,
      shiftStartMins: hhmmToMins(parseShiftTime(f.startTime)),
      shiftEndMins:   hhmmToMins(parseShiftTime(f.endTime)),
    })),
    // ISS staff are excluded from the coverer pool — they self-manage their own breaks
    // and should not be assigned to cover room staff lunch breaks.
    // Support staff (AD/Ed Leader) as last resort when no float/ISS available
    ...eligibleSupport.map(s => ({
      id:             s.employeeId,
      name:           s.employeeName,
      type:           'support' as const,
      nextAvailMins:  windowStart,
      shiftStartMins: hhmmToMins(parseShiftTime(s.startTime)),
      shiftEndMins:   hhmmToMins(parseShiftTime(s.endTime)),
    })),
  ];

  const entries: LunchBreakEntry[] = [];

  // ── Pass 1: Self-covered rooms (surplus ≥ 1) ─────────────────────────────
  // Rooms where there's at least one spare person — breaks stagger evenly,
  // no float needed. These are independent of float scheduling.
  for (const rs of roomStatuses) {
    const n      = rs.rosteredStaff.length;
    if (n === 0) continue;
    const surplus = Math.max(0, n - rs.requiredStaff);
    if (surplus === 0) continue; // handled in pass 2

    const windowDuration = windowEnd - windowStart;
    const slotGap        = Math.max(dur, Math.floor(windowDuration / n));
    const sorted         = [...rs.rosteredStaff].sort((a, b) =>
      hhmmToMins(parseShiftTime(a.startTime)) - hhmmToMins(parseShiftTime(b.startTime))
    );

    sorted.forEach((s, idx) => {
      const shiftStart    = hhmmToMins(parseShiftTime(s.startTime));
      const shiftEnd      = hhmmToMins(parseShiftTime(s.endTime));
      const earliestBreak = Math.max(windowStart, shiftStart + 60);
      const latestBreak   = Math.min(windowEnd - dur, shiftEnd - dur - 30);
      if (latestBreak < earliestBreak) return;

      const lunchStartMins = Math.max(earliestBreak, Math.min(windowStart + idx * slotGap, latestBreak));
      const lunchEndMins   = lunchStartMins + dur;

      // Find a colleague not on break at the same time
      const colleague = sorted.find((_o, oIdx) => {
        if (oIdx === idx) return false;
        const oStart = windowStart + oIdx * slotGap;
        return !(oStart < lunchEndMins && oStart + dur > lunchStartMins);
      });

      entries.push({
        employeeId:    s.employeeId,
        name:          s.employeeName,
        room:          rs.room.name,
        shiftStart:    parseShiftTime(s.startTime),
        shiftEnd:      parseShiftTime(s.endTime),
        lunchStart:    minsToHHMM(lunchStartMins),
        lunchEnd:      minsToHHMM(lunchEndMins),
        coveredBy:     colleague
          ? { name: colleague.employeeName, employeeId: colleague.employeeId, type: 'surplus' }
          : null,
        needsCover:    !colleague,
        autoGenerated: true,
      });
    });
  }

  // ── Pass 2: Float-covered rooms (surplus = 0) — sequential assignment ────
  //
  // Key principle: floats are NOT tied to one room. Once a float finishes
  // covering a break in Room A, they immediately move to the next break —
  // whether that's another staff member in Room A or someone in Room B.
  //
  // We collect ALL staff from ALL exact-ratio rooms into one flat queue,
  // sort by earliest viable break time, then chain breaks back-to-back.

  const floatQueue: {
    rs: RoomRatioStatus;
    s: RosteredStaff;
    earliestBreak: number;
    latestBreak:   number;
  }[] = [];

  for (const rs of roomStatuses) {
    const n      = rs.rosteredStaff.length;
    if (n === 0) continue;
    const surplus = Math.max(0, n - rs.requiredStaff);
    if (surplus > 0) continue; // already handled above

    for (const s of rs.rosteredStaff) {
      const shiftStart    = hhmmToMins(parseShiftTime(s.startTime));
      const shiftEnd      = hhmmToMins(parseShiftTime(s.endTime));
      const earliestBreak = Math.max(windowStart, shiftStart + 60);
      const latestBreak   = Math.min(windowEnd - dur, shiftEnd - dur - 30);
      if (latestBreak < earliestBreak) continue; // shift doesn't fit in window
      floatQueue.push({ rs, s, earliestBreak, latestBreak });
    }
  }

  // Sort: earliest shift-starters go first (7am before 8am before 9am).
  // This is best practice — those who started longest ago go to lunch first.
  // Use earliestBreak as tiebreaker when shifts start at the same time.
  floatQueue.sort((a, b) => {
    const aStart = hhmmToMins(parseShiftTime(a.s.startTime));
    const bStart = hhmmToMins(parseShiftTime(b.s.startTime));
    if (aStart !== bStart) return aStart - bStart;
    return a.earliestBreak - b.earliestBreak || a.latestBreak - b.latestBreak;
  });

  for (const { rs, s, earliestBreak, latestBreak } of floatQueue) {
    // Find the first coverer who:
    //  (a) becomes available before this person's latest possible break
    //  (b) can finish the break (dur) before their own shift ends
    const coverer = covererPool.find(c => {
      const coverStart = Math.max(earliestBreak, c.nextAvailMins);
      return coverStart <= latestBreak && coverStart + dur <= c.shiftEndMins;
    });

    let lunchStartMins: number;
    let coveredBy: CoverageInfo | null = null;

    if (coverer) {
      // Start break when the coverer becomes free (but not before staff's earliest)
      lunchStartMins = Math.max(earliestBreak, coverer.nextAvailMins);
      lunchStartMins = Math.min(lunchStartMins, latestBreak); // clamp to window
      coveredBy = { name: coverer.name, employeeId: coverer.id, type: coverer.type };
      coverer.nextAvailMins = lunchStartMins + dur; // coverer busy until this break ends
    } else {
      // No coverer available — place at earliest time, flag as uncovered
      lunchStartMins = earliestBreak;
    }

    entries.push({
      employeeId:    s.employeeId,
      name:          s.employeeName,
      room:          rs.room.name,
      shiftStart:    parseShiftTime(s.startTime),
      shiftEnd:      parseShiftTime(s.endTime),
      lunchStart:    minsToHHMM(lunchStartMins),
      lunchEnd:      minsToHHMM(lunchStartMins + dur),
      coveredBy,
      needsCover:    !coveredBy,
      autoGenerated: true,
    });
  }

  // ── Pass 3: Float / ISS own lunch breaks ────────────────────────────────
  //
  // Floaters cover room staff all morning/afternoon — they need a break too.
  // ISS staff are excluded: they self-manage their own lunch breaks and should
  // not consume float availability or appear in the lunch panel.
  // Support staff (AD/Ed Leader) are also excluded.

  for (const coverer of covererPool.filter(c => c.type === 'float')) {
    // Earliest the break can start: when they finish covering room staff,
    // but not before their shift or the window opens.
    const earliest = Math.max(
      coverer.nextAvailMins,
      windowStart,
      coverer.shiftStartMins + 60,
    );
    const latest = Math.min(windowEnd - dur, coverer.shiftEndMins - dur - 15);
    if (latest < earliest) continue; // no viable slot in window

    const breakStart = Math.min(earliest, latest);

    // See if another coverer can cover this float’s break
    const backup = covererPool.find(c =>
      c.id !== coverer.id &&
      c.nextAvailMins <= breakStart &&
      breakStart + dur <= c.shiftEndMins
    );

    entries.push({
      employeeId:    coverer.id,
      name:          coverer.name,
      room:          coverer.type === 'float' ? 'Float' : 'ISS',
      shiftStart:    minsToHHMM(coverer.shiftStartMins),
      shiftEnd:      minsToHHMM(coverer.shiftEndMins),
      lunchStart:    minsToHHMM(breakStart),
      lunchEnd:      minsToHHMM(breakStart + dur),
      coveredBy:     backup
        ? { name: backup.name, employeeId: backup.id, type: backup.type }
        : null,
      // Floaters aren’t assigned to a ratio room, so ratio isn’t breached
      // when they’re on break — flag needsCover only if another float is needed
      needsCover:    false,
      autoGenerated: true,
    });

    // Mark this floater as busy during their own break
    coverer.nextAvailMins = breakStart + dur;
    // Mark the backup as busy too if assigned
    if (backup) backup.nextAvailMins = breakStart + dur;
  }

  // Sort final schedule by break start time
  return entries.sort((a, b) => hhmmToMins(a.lunchStart) - hhmmToMins(b.lunchStart));
}
